name: "Rust Clippy"

on:
  push:
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
  pull_request:
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
